export const ACTION_TYPES = {
  INIT_LIST: "INIT_LIST",
  SELECT_LIST: "SELECT_LIST",

  ADD_LIST: "ADD_LIST",
  RENAME_LIST: "RENAME_LIST",
  DELETE_LIST: "DELETE_LIST",

  ADD_TASK: "ADD_TASK",
  UPDATE_TASK_TITLE: "UPDATE_TASK_TITLE",
  TOGGLE_TASK_COMPLETION: "TOGGLE_TASK_COMPLETION",
  TOGGLE_TASK_IMPORTANCE: "TOGGLE_TASK_IMPORTANCE",
  DELETE_TASK: "DELETE_TASK",
};
