export const ACTION_TYPES = {
  INIT_LIST: "INIT_LIST",

  ADD_LIST: "ADD_LIST",
  RENAME_LIST: "RENAME_LIST",
  DELETE_LIST: "DELETE_LIST",

  ADD_TASK: "ADD_TASK",
  MOVE_TASK: "MOVE_TASK",
  UPDATE_TASK_TITLE: "UPDATE_TASK_TITLE",
  TOGGLE_TASK_COMPLETION: "TOGGLE_TASK_COMPLETION",
  TOGGLE_TASK_IMPORTANCE: "TOGGLE_TASK_IMPORTANCE",
  UPDATE_TASK_NOTES: "UPDATE_TASK_NOTES",
  SET_TASK_DUE_DATE: "SET_TASK_DUE_DATE",
  SET_TASK_REMINDER_TIME: "SET_TASK_REMINDER_TIME",
  DELETE_TASK: "DELETE_TASK",

  SET_THEME_COLOR: "SET_THEME_COLOR",
  SET_TASK_SORT_ORDER: "SET_TASK_SORT_ORDER",
  TOGGLE_SHOW_COMPLETED_TASKS: "TOGGLE_SHOW_COMPLETED_TASKS",
};
